service: tile-caching
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x     
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - s3:*
          Resource: 
            - "arn:aws:s3:::poster-boi-data-dump"
            - "arn:aws:s3:::poster-boi-data-dump/*"

plugins:
  - serverless-dotenv-plugin
  - serverless-iam-roles-per-function

functions:
  get:
    handler: src/get-lambda.invoke
    events:
      - httpApi:
          path: /
          method: get
